kind: Service
apiVersion: v1
metadata:
  name: reservation-business-services
spec:
  selector:
      app: reservation-business-services
  ports:
    - port: 80
      targetPort: 8004
  type: LoadBalancer
