apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-services
spec:
  selector:
      matchLabels:
        app: room-services
        tier: backend
        track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: room-services
        tier: backend
        track: stable        
    spec:
      containers:
        - name: room-services
          image: freddybendezu/room-services
          ports:
            - name: http
              containerPort: 8001