apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-service
spec:
  selector:
      matchLabels:
        app: room-service
        tier: backend
        track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: room-service
        tier: backend
        track: stable        
    spec:
      containers:
        - name: room-service
          image: ryuk2105/room-service
          ports:
            - name: http
              containerPort: 8001